# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A9s < Formula
  desc "The k9s for AWS - Interactive Terminal UI for AWS"
  homepage "https://github.com/keanuharrell/a9s"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/keanuharrell/a9s/releases/download/v0.2.6/a9s_0.2.6_Darwin_amd64.tar.gz"
      sha256 "c1b03f7f50e5a68e817a48aae791939b642bdcd599494fdfeb6e7c79d0cfce91"

      def install
        bin.install "a9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/keanuharrell/a9s/releases/download/v0.2.6/a9s_0.2.6_Darwin_arm64.tar.gz"
      sha256 "c24450f7d9360422a1aa3b018b228b4da7a5732fb28219163dfa502d6fc096b4"

      def install
        bin.install "a9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/keanuharrell/a9s/releases/download/v0.2.6/a9s_0.2.6_Linux_amd64.tar.gz"
      sha256 "e9e47743c2bc49d54287c188c24783cd63380198fbbd6e9632096c17a52b171c"
      def install
        bin.install "a9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/keanuharrell/a9s/releases/download/v0.2.6/a9s_0.2.6_Linux_arm64.tar.gz"
      sha256 "ea43f174639624ca7762cf0b6e1bf6713f5c4534ff1aff599a2e5703c694fbf1"
      def install
        bin.install "a9s"
      end
    end
  end

  test do
    system "#{bin}/a9s", "--version"
  end
end
